### ISSUE TITLE
Codeship this

### ISSUE THREAD

**Issue by bitboxer** [eurucamp/livingstyleguide-eurucamp#10]
@bascht this needs to be codeshiped. Can you talk to @hagenburger about this? :heart:

**Comment by bascht** [comment]
@bitboxer sure. Can you gpgmail me the details of the S3 account this is pushed to?

**Comment by bitboxer** [comment]
@bascht sorry for the late reply, but now you have the s3 in your inbox.

**Comment by hagenburger** [comment]
So my needs:

- [ ] Automatically deploy after each push into any branch
- [ ] Prefix with the latest commit’s short hash code: http://style-guide.eurucamp.org/81c336/
- [ ] Create an index file at http://style-guide.eurucamp.org/ listing all deploys with:
    * Link
    * Last commit date, user, message
    * Most recent deploy on top
- [ ] Mirroring http://style-guide.eurucamp.org/latest/ to most recent deploy
- [ ] A robots.txt disallowing to index everything except the index and latest

**Comment by bascht** [comment]
@hagenburger on it.
@bitboxer can you give me admin access to the repo so I can add it to codeship?

**Comment by bitboxer** [comment]
Done!

**Comment by bascht** [comment]
@bitboxer Thank you!
@hagenburger Take a look at http://style-guide.eurucamp.org and add colors / fonts as much as you please. ;)

**Comment by bascht** [comment]
(I only keep current build artefacts, so until we have > 10 commits some of those links will 404)

**Comment by hagenburger** [comment]
@bascht thanks! I’ll add styles when I’m back home.

**Comment by bascht** [comment]
@hagenburger This issue is resolved, isn't it? If yes → close. :)

**Comment by hagenburger** [comment]
Yes, thanks!
