### ISSUE TITLE
Shared partials for all websites

### ISSUE THREAD

**Issue by hagenburger** [eurucamp/livingstyleguide-eurucamp#6]
Create shared static partials downloadable partials:

  * [x] `<head>` (load stylesheets, etc.)
  * [x] Header (static navigation; maintained in style guide only)
  * [x] Footer (static navigation; maintained in style guide only)

**Comment by bascht** [comment]
Looks like this was solved in 627b6531a4578c98a89c60c7383444570fb20b8d. :)
